# Generated by Django 2.2 on 2020-04-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playernames',
            name='position',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
