# Generated by Django 2.2 on 2020-04-20 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_playernames_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playernames',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='playernames',
            name='updated_at',
        ),
    ]
