# Generated by Django 2.2 on 2020-04-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200420_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playernames',
            name='id',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
