# Generated by Django 2.2 on 2020-04-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200420_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='playernames',
            name='position_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
