# Generated by Django 2.2 on 2020-05-08 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_playernames_position_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictedTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gw_01', models.CharField(blank=True, max_length=250, null=True)),
                ('gw_02', models.CharField(blank=True, max_length=250, null=True)),
                ('gw_03', models.CharField(blank=True, max_length=250, null=True)),
                ('gw_04', models.CharField(blank=True, max_length=250, null=True)),
                ('gw_05', models.CharField(blank=True, max_length=250, null=True)),
                ('gw_06', models.CharField(blank=True, max_length=250, null=True)),
                ('gw_07', models.CharField(blank=True, max_length=250, null=True)),
                ('gw_08', models.CharField(blank=True, max_length=250, null=True)),
                ('gw_09', models.CharField(blank=True, max_length=250, null=True)),
                ('gw_10', models.CharField(blank=True, max_length=250, null=True)),
                ('gw_11', models.CharField(blank=True, max_length=250, null=True)),
                ('gw_12', models.CharField(blank=True, max_length=250, null=True)),
                ('gw_13', models.CharField(blank=True, max_length=250, null=True)),
                ('gw_14', models.CharField(blank=True, max_length=250, null=True)),
                ('gw_15', models.CharField(blank=True, max_length=250, null=True)),
                ('gw_16', models.CharField(blank=True, max_length=250, null=True)),
                ('gw_17', models.CharField(blank=True, max_length=250, null=True)),
                ('gw_18', models.CharField(blank=True, max_length=250, null=True)),
                ('gw_19', models.CharField(blank=True, max_length=250, null=True)),
                ('gw_20', models.CharField(blank=True, max_length=250, null=True)),
                ('gw_21', models.CharField(blank=True, max_length=250, null=True)),
                ('gw_22', models.CharField(blank=True, max_length=250, null=True)),
                ('gw_23', models.CharField(blank=True, max_length=250, null=True)),
                ('gw_24', models.CharField(blank=True, max_length=250, null=True)),
                ('gw_25', models.CharField(blank=True, max_length=250, null=True)),
                ('gw_26', models.CharField(blank=True, max_length=250, null=True)),
                ('gw_27', models.CharField(blank=True, max_length=250, null=True)),
                ('gw_28', models.CharField(blank=True, max_length=250, null=True)),
                ('gw_29', models.CharField(blank=True, max_length=250, null=True)),
                ('gw_30', models.CharField(blank=True, max_length=250, null=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PlayerNames')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameweek_one_score', models.FloatField(blank=True, null=True)),
                ('player_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PlayerNames')),
            ],
        ),
    ]
