# Generated by Django 2.2 on 2020-05-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_playerscores_predictedtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictedtable',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
