# Generated by Django 2.2 on 2020-05-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200508_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonFixtures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameweek', models.IntegerField(blank=True, null=True)),
                ('home_team', models.CharField(max_length=250)),
                ('away_team', models.CharField(max_length=250)),
            ],
        ),
    ]
