# Generated by Django 2.2 on 2020-05-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_seasonfixtures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonfixtures',
            name='away_team',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='seasonfixtures',
            name='home_team',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
