# Generated by Django 2.2 on 2020-06-09 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200524_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerscores',
            old_name='gameweek_one_score',
            new_name='gw_01',
        ),
        migrations.RemoveField(
            model_name='predictedtable',
            name='gw_02',
        ),
        migrations.AddField(
            model_name='playerscores',
            name='gw_02',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerscores',
            name='gw_03',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerscores',
            name='gw_04',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerscores',
            name='gw_05',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerscores',
            name='gw_06',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerscores',
            name='gw_07',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerscores',
            name='gw_08',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerscores',
            name='gw_09',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerscores',
            name='gw_10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerscores',
            name='gw_11',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerscores',
            name='gw_12',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerscores',
            name='gw_13',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerscores',
            name='gw_14',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerscores',
            name='gw_15',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerscores',
            name='gw_16',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerscores',
            name='gw_17',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerscores',
            name='gw_18',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerscores',
            name='gw_19',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerscores',
            name='gw_20',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerscores',
            name='gw_21',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerscores',
            name='gw_22',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerscores',
            name='gw_23',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerscores',
            name='gw_24',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerscores',
            name='gw_25',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerscores',
            name='gw_26',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerscores',
            name='gw_27',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerscores',
            name='gw_28',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerscores',
            name='gw_29',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerscores',
            name='player_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.PlayerNames'),
        ),
    ]
