# Generated by Django 2.2 on 2020-06-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200609_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerscores',
            name='player_name',
        ),
        migrations.AddField(
            model_name='playerscores',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='playerscores',
            name='position',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='playerscores',
            name='position_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerscores',
            name='team',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
