# Generated by Django 2.2 on 2020-06-12 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_firstweekpred'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firstweekpred',
            old_name='Names',
            new_name='name',
        ),
    ]
